export const UPDATE_CALENDAR_MONTH = 'UPDATE_CALENDAR_MONTH';
export const UPDATE_DISPLAYTYPE_SELECT = 'UPDATE_DISPLAYTYPE_SELECT';

export const SHOW_CONTEXTMENU = 'SHOW_CONTEXTMENU';
export const HIDE_CONTEXTMENU = 'HIDE_CONTEXTMENU';
