export const UPDATE_CALENDAR_MONTH = "UPDATE_CALENDAR_MONTH";
export const UPDATE_DISPLAYTYPE_SELECT = "UPDATE_DISPLAYTYPE_SELECT";

export const SHOW_CONTEXTMENU = "SHOW_CONTEXTMENU";
export const HIDE_CONTEXTMENU = "HIDE_CONTEXTMENU";

//BoxContent Action
export const ADD_FRAME = "ADD_FRAME";
export const REMOVE_FRAME = "REMOVE_FRAME";
export const MOVE_FRAME = "MOVE_FRAME";
export const ADD_MEMORY = "ADD_MEMORY";
export const UPDATE_MEMORY = "UPDATE_MEMORY";
